import Header from "@/components/header";
import Head from "next/head";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Nexts Mini Project</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 h-screen overflow-y-scroll">
        <div className="w-[400px] mx-auto bg-white">
          <Header />
          <main className="p-4">{children}</main>
        </div>
      </div>
    </>
  );
};

export default Layout;
